### ISSUE TITLE
Searchable documentation

### ISSUE THREAD

**Issue by ThomasAdam** [neomutt/neomutt-docs#5]
How do we make the manual searchable?

Can we use some sort of framework for this?  Less important to be able to do this "off-line" (that is, locally -- although if that's supported, great!).

But for the hosted version on the website, this would be important.

**Comment by ghost** [comment]
I guess this can be closed.

* Website searching is available through [algolia](https://github.com/neomutt/neomutt.github.io/commit/eab2af9b6f3e94a4347bc6293fe0005aeb7e5e93) and the webbrowser's searching ability (strg-F on firefox)

* offline searching can be done with tools such as grep or [the_silver_searcher](https://github.com/ggreer/the_silver_searcher).

Of course both can be improved but i think that can be moved to another issue (especially because the website is in a different repo)
